- package.json
- src/Functions/Files/preview.js
- src/public/style.css
- yarn.lock
> Support markdown preview

- src/Components/contextMenu.js
- src/Components/drives.js
- src/Components/home.js
- src/Components/shortcut.js
- src/Components/tab.js
- src/Components/windowManager.js
- src/Constants/windowGUID.js
- src/Functions/Files/new.js
- src/Functions/Files/open.js
- src/Functions/Tab/changePosition.js
- src/main.js
Support opening multiple xplorer windows.
> Support multiple windows

- docs/docs/intro.md
- docs/docusaurus.config.js
- docs/i18n/id/code.json
- docs/i18n/id/docusaurus-plugin-content-docs-community/current.json
- docs/i18n/id/docusaurus-plugin-content-docs/current.json
- docs/i18n/id/docusaurus-plugin-content-docs/current/feature/_category_.json
- docs/i18n/id/docusaurus-plugin-content-docs/current/feature/file operation.md
- docs/i18n/id/docusaurus-plugin-content-docs/current/feature/shortcut.md
- docs/i18n/id/docusaurus-plugin-content-docs/current/installation/Linux.md
- docs/i18n/id/docusaurus-plugin-content-docs/current/installation/Windows.md
- docs/i18n/id/docusaurus-plugin-content-docs/current/installation/_category_.json
- docs/i18n/id/docusaurus-plugin-content-docs/current/intro.md
- docs/i18n/id/docusaurus-plugin-content-pages/components/HomepageFeatures.js
- docs/i18n/id/docusaurus-plugin-content-pages/components/HomepageFeatures.module.css
- docs/i18n/id/docusaurus-plugin-content-pages/index.js
- docs/i18n/id/docusaurus-plugin-content-pages/index.module.css
- docs/i18n/id/docusaurus-theme-classic/footer.json
- docs/i18n/id/docusaurus-theme-classic/navbar.json
Add Bahasa Indonesia langauge on docs
> docs: Indonesian docs

- src/Locales/de-DE.json
- src/Locales/index.json
Add a German translation
de-DE.json, index.json
> German translation

- src/Components/ContextMenu/contextMenu.ts
- src/Components/Files/File Operation/open.ts
- src/Components/Layout/home.ts
This issue #59 about file/folder max character length.
Limit the character length in large, medium, and small grid layout.
Please take a look at these images below:
Issue #59 
_none_
> fix: File/Folder max character length

- src/Locales/fr-FR.json
- src/Locales/index.json
I appreciate the project. I would like to contribute with my language 😄
Added French translation.
https://github.com/kimlimjustin/xplorer/discussions/30#discussioncomment-1396432
> Added french translation

- README.md
Open-source Contribution
Fix Icon that was showing a broken image
Should I use the icons that are present in the `docs/static/img/icons/` or is this fine?
> Fix image icon in README.md

- docs/src/pages/index.jsx
> Change Preview-file docs link in Homepage

- src/Components/Shortcut/shortcut.ts
Add the ability to navigate with additional mouse keys
Added a new event listener for the mouse buttons
#58
> feat(shortcuts): navigation with additional mouse keys (#58)

- docs/community/Contributing.md
Open Source Contribution
Fix broken Github links to File Icon and File type
> Fix broken Github links to File Icon and File type

- scripts/copyfiles.js
remove unused require() from copyfiles.js
> chore(copyfiles): unused require

- package.json
- yarn.lock
> chore: move jest to dev dependencies

- README.md
- docs/README.md
Open Source Contribution
- Update README
- typos
- reframe sentences
- add/fix links
> Update README, fix typo and sentences

- docs/src/pages/index.jsx
Open Source Contribution
- Fix typo in Homepage `oraganize`->`organize`
> Fix typo in homepage

- src/Components/Files/files.scss
- src/Components/Theme/theme.json
(Changed some style properties for Dark+ mode > Top bar and grid hover. And in Light and Light+ Mode to look good from user experience.)
> Style properties

- src/Components/Setting/setting.scss
- src/Components/Setting/setting.ts
- src/Components/Theme/theme.json
- src/Components/Theme/theme.ts
- yarn.lock
Sometimes people find difficulties in recognizing which tab is currently opened. Therefore by adding some styling will allow them to cope with this issue.
- Added `setActiveTab` function
- Added Active Tab Styling
- Set `onmouseleave` attribute to null when tab is active
Light:
Dark:
Light+:
Dark+:
> Added Active Tab Styling in Settings

- .gitignore
- src/Components/Files/File Operation/select.ts
- src/Components/Functions/lazyLoadingImage.ts
- src/Components/Theme/theme.ts
Reduce duplicated code. Duplicated code could cause issues related to the missed bug fixes in some place of the source code.
Moved duplicated code to separate functions.
> Reduce duplicated code

- docs/i18n/de-DE/docusaurus-plugin-content-pages/index.jsx
- docs/i18n/de-DE/docusaurus-plugin-content-pages/slideshow.jsx
- docs/i18n/id-ID/docusaurus-plugin-content-pages/index.jsx
- docs/i18n/id-ID/docusaurus-plugin-content-pages/slideshow.jsx
- docs/i18n/pt-BR/docusaurus-plugin-content-pages/index.jsx
- docs/i18n/pt-BR/docusaurus-plugin-content-pages/slideshow.jsx
- docs/i18n/ru-RU/docusaurus-plugin-content-pages/index.jsx
- docs/i18n/ru-RU/docusaurus-plugin-content-pages/slideshow.jsx
- docs/i18n/zh-CN/docusaurus-plugin-content-pages/index.jsx
- docs/i18n/zh-CN/docusaurus-plugin-content-pages/slideshow.jsx
- docs/i18n/zh-TW/docusaurus-plugin-content-pages/index.jsx
- docs/i18n/zh-TW/docusaurus-plugin-content-pages/slideshow.jsx
- docs/src/css/custom.css
- docs/src/pages/index.jsx
- docs/src/pages/slideshow.jsx
- Fix Slideshows not displaying images on other languages homepage
- Use `<Link>` tags in other languages homepage
- fix file-preview link in other languages homepage
- Add `sans-serif` fallback font
- Combine google-fonts URL
- Fixes #122
> Fix Slideshows not displaying images for other languages

- package.json
- patches/fast-folder-size+1.4.0.patch
- src/Components/Properties/properties.ts
- yarn.lock
It'd be better if we can calculate the size of a folder.
- add `fast-folder-size` dependency.
- add size property to folder
resolve #76
Could you please review this? @stanleyowen
> feat: add size property for folder (#76)

- .gitpod.yml
- Dockerfile
- README.md
- docs/docs/Community/Contributing.md
Gitpod has not worked since the merging of #173, this PR makes it work again
- Rename `.gitpod.Dockerfile` to Dockerfile
- Add tauri deps into dockerfile
- Update gitpod configuration
#173
@im-coder-lg please review this.
<a href="https://gitpod.io/#https://github.com/kimlimjustin/xplorer/pull/197"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> refactor<gp>: make gitpod works with tauri

- README.md
- docs/docs/intro.md
Found some broken links
Fixed broken links :)
<a href="https://gitpod.io/#https://github.com/kimlimjustin/xplorer/pull/210"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix broken links

- docs/src/css/custom.css
- docs/src/pages/support.jsx
Open-source ❤️ 
- use css custom variables to update primary text color of some elements in themes
- remove displaying dependabot from contributor list.
<a href="https://gitpod.io/#https://github.com/kimlimjustin/xplorer/pull/211"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix text readability in dark theme and remove dependabot from contributor

- src/Api/storage.ts
- src/Components/Layout/layout.scss
- src/Components/Layout/resizer.ts
- src/Components/Shortcut/shortcut.ts
- src/Public/style.scss
- src/Typings/storageData.d.ts
- src/index.html
- src/index.ts
* Sidebar edge too small to grab.
* Setting sidebar doesn't update along with `Ctrl+B`.
* Shrinking icons when resizing.
* Laggy transition when changing label of minimized sidebar.
* Various repeating codes.
* Removed sidebar edge element, added edge listener.
* Gathered resizing functions.
* Fixed icon sizes.
* Reduced fast searching time to `400ms`.
<a href="https://gitpod.io/#https://github.com/kimlimjustin/xplorer/pull/219"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update sidebar resizer

- src-tauri/src/files_api.rs
- src-tauri/src/main.rs
- src/Service/operation.ts
- fix unworking permanently deleting files/dirs
- fix unworking copy files operation
- fix unworking rename files operation
<a href="https://gitpod.io/#https://github.com/kimlimjustin/xplorer/pull/241"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: not working file operations due to tauri update

- docs/docs/guides/setting.md
- src-tauri/src/files_api.rs
- src/Components/Open/displayFiles.ts
- src/Components/Setting/Preference/preference.ts
- src/Locales/base.json
#245 
* Enable option to calculate subfolder size
* Update the documentation related to this PR
* Update the i18n list
<a href="https://gitpod.io/#https://github.com/kimlimjustin/xplorer/pull/246"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat: calculate subfolder size

- docs/docs/install.md
Spelling was wrong in english
Updated the info text for installation on arch distro Linux.
`Use you favourite` -> `Use your favourite`
[Installation on Arch](https://xplorer.space/docs/install/#arch-based-distros) section
<a href="https://gitpod.io/#https://github.com/kimlimjustin/xplorer/pull/262"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Docs: Update installation info for arch distro

- docs/src/pages/support.jsx
filter bots from response and fix site crash on ratelimit
the contributors endpoint only returns a max of 30 contributors, so there is no need to slice on it.
<a href="https://gitpod.io/#https://github.com/kimlimjustin/xplorer/pull/266"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> filter out bots from response and fix site crash on ratelimit

- scripts/generate-fake-files.py
- src/Components/ContextMenu/configs/multipleSelectedMenu.config.ts
- src/Components/Layout/home.ts
Some bad code is found, this PR is intended to remove those inefficiencies code
<a href="https://gitpod.io/#https://github.com/kimlimjustin/xplorer/pull/271"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> refactor: code inefficiencies

- src/Components/Files/File Operation/select.ts
- src/Components/Layout/layout.scss
- src/Typings/select.d.ts
I was getting crazy for this missing functionality.
I didn't change almost anything of the existing code, I added the functionality that lets users to drag-select multiple items with mouse.
<a href="https://gitpod.io/#https://github.com/kimlimjustin/xplorer/pull/273"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add: mouse drag selection

- docs/docs/intro.md
Changing 2022 to 2023 (Minor change)
Changed from 2022 to 2023 --> "...customizable to fit 2022's need. Besides..."
> Update intro.md's year
