kimlimjustin/xplorer

- docs/docs/guides/cli.md
- docs/package.json
- docs/yarn.lock
- src/Components/Context Menu/contextMenu.ts
- src/Components/Files/File Operation/open.ts
- src/Components/Layout/tab.ts
- src/Components/Layout/windowManager.ts
- src/Components/Shortcut/shortcut.ts
- src/main.ts
- src/preload.ts
It would be nice if users are able to launch Xplorer from the terminal.
* Add `yargs` dependencies
* Add basic cli functions, including the `reveal` flag
* Update the docs
> Xplorer Cli

- README.md
Was just looking around after a post on dev.to and was a little confused by the `not` until I realized it was a `note`.
Fix typo `not` to `note`. Also changed another word that, for me, sounds slightly better but may be up to discussion.
> docs: fix typo in readme and small rephrase

- docs/community/CODE_OF_CONDUCT.md
- docs/community/Contributing.md
- docs/community/support.md
- docs/docs/guides/cli.md
- docs/docs/guides/operation.md
- docs/docs/guides/setting.md
- docs/docs/guides/xplorer as default.md
- docs/docs/install.md
- docs/docs/intro.md
There were a lot of grammatical and typing mistakes in docs section.
Fixed all of it
> docs: fix typos and grammar on pages

- src/Components/Setting/setting.scss
- src/Public/index.html
Close settings button was not entirely clickable. User had to click on the up-arrow icon (↑) to close it.
Bug fixed. Added the `exit-setting-btn` class to parent which was previously added to up-arrow icon. Adding this made the whole close/exit settings button clickable.
Issue #61
> fix: make close settings button clickable

- src/Public/index.html
Spell check was in place at the file path input which resulted in red swiggly lines below texts. That didn't look nice!
Adding spellcheck="false" attribute to `input type="text"` resolved it. 
Issue #70
> bug: disable spell check on filepath input

- src/Components/Shortcut/shortcut.ts
Whenever file path navigator was in focus, pressing keyboard shortcuts worked. For example, when input was focused, pressing CTRL+SHIFT+N opened up new folder window. Similarly, happened for other keyboard shortcuts.
Patched it with a simple check if keyboard shortcut gets triggered and input is already in focus mode, ignore it.
Issue #70
> bug: ignore keyboard shortcuts if filepath navigator is in focus

- src/Components/Properties/properties.scss
After clicking on file properties, it shows perfectly but when close properties, it stay on right side corner when filename/filepath consist of more characters.
keyframes for `close-properties` rule was set to `right: -50vw` instead of `-100vw`
Issue: #72 #54
> bug: make properties box exit entirely when closed

- src/Components/Files/File Operation/open.ts
- src/Components/Layout/windowManager.ts
Seems pointless to try to walk an empty path
Added a check for the presence of a path before the navigate
> Do not navigate if the path navigator is empty

- src/Components/Files/File Operation/select.ts
Supplement #73 
Adds check to ignore arrow keys for select files if path navigator has focus
#73
> Ignore arrow keys for select files if path navigator has focus

- docs/src/css/custom.css
- docs/src/pages/slideshow.jsx
The origin slide animation is not fluent. 
The previous image is disappeared but not fade out.
This PR is to optimize the animation effect and the out-of-date React code.
- use React state instead of control DOM element
- use transition instead of keyframe animation
Origin slide
New slide
> optimize doc index page slide show animation and refactor related React code

- src/Locales/index.json
Just removed the unnecessary clarification that this is a language (язык) and made the word "русский" (russian) with a uppercase letter
> fix(locales): remove unnecessary explanation from the "русский язык"

- docs/blog/2021-08-09-introduction.md
- docs/community/Contributing.md
- docs/community/support.md
- docs/docs/common_problems.md
- docs/docs/guides/cli.md
- docs/docs/guides/setting.md
- docs/docs/install.md
- docs/docs/intro.md
I observed that the docs have a lot of grammatical errors so I am aiming to fix it through this PR
Almost every single file in the documentation(mostly the important ones)
Nothing related here as of now.
I could finish everything in a week since the docs have a lot of files, I need to go through them when I am free, and I have a genuine suggestion: Last time, you said that Docusaurus is buggy sometimes, so why not use CODEDOC? CODEDOC is another documentation source like Docusaurus and everything there is really minimal. You get a footer, where you can link your repository, add starring buttons, link a Gitter community(if you want) and create custom components from TypeScript. So, if you want to switch, you can ask me anytime. Documentation of CODEDOC is over on https://codedoc.cc and …
> fix(docs): Grammatical Error correction

- docs/docs/install.md
You can use `<code>` tags instead of `<kbd>` where markdown backtics don't work.
> Use <code> instead of <kbd>

- README.md
> Remove duplicate feature lists

- src/main.ts
Xplorer can't be opened on Applications on Windows 10 but it can via CLI, hence here's the PR that solves it.
#138 
@stanleyowen  could you please try this together with the theme customization?
> fix: cannot be opened on Windows 10 (resolve #138)

- src/Components/Files/File Operation/open.ts
- src/Components/Files/files.scss
As a result of merging #89, files/folders with name more than 30 characters won't able to be operated because as #89 only take file name up to 30 characters.
Use CSS to resolve character limits
#89 #126 
Could you please review this? @dkhd
> fix: files with file name more than 30 characters won't able to be operated

- src/Components/Properties/properties.scss
- src/Components/Properties/properties.ts
- src/Components/Theme/theme.json
##Changes
-- Placed properties box in center bottom and applied some CSS.
> Properties Style

- src-tauri/src/files_api.rs
- src-tauri/src/main.rs
- src-tauri/src/storage.rs
- src/Api/files.ts
- src/Components/Files/File Operation/new.ts
- src/Components/Files/File Operation/select.ts
- src/Components/Layout/infobar.ts
- src/Components/Layout/layout.scss
- src/Components/Open/displayFiles.ts
- src/Components/Open/open.ts
- src/Components/Setting/Appearance/Appearance.ts
- src/Components/Shortcut/shortcut.ts
- src/Components/Theme/theme.json
- src/Components/Theme/theme.ts
- src/Locales/base.json
- src/index.ts
It'd be nice if there's a bar on the bottom showing number of files and information of currently selected files like what File Explorer does.
- Add the infobar layout
- Add number of files and current selected files information into infobar
> feat: Infobar

- docs/src/css/custom.css
- docs/src/pages/index.jsx
- docs/src/pages/slideshow.jsx
This PR was created to improve the professionalism of the documentation site.
Updated the `docs/src/pages/slideshow.jsx` component to support user-selecting specific images within the slideshow. Previously users had to wait until the slideshow cycled to re-view an image. Now users can simply click on the dot corresponding to their desired image and that image will show. Note that after clicking on a dot the image will still cycle after a given period of time (configured in the component).
_These buttons can now be used to view specific images within the slideshow_
Currently images within the docs homepage (`docs/src/pages/index.jsx`) do not display properly on small screens. This was fixed using the `object-fit` [CSS rule](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit). …
> Added slide selection and fixed image overflow for small screen sizes

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/files_api.rs
- src-tauri/src/main.rs
- src/Api/directory.ts
- src/Components/Files/File Operation/search.ts
- src/Components/Functions/changePosition.ts
- src/Components/Layout/hover.ts
- src/Components/Layout/layout.scss
- src/Components/Open/displayFiles.ts
- src/Components/Open/open.ts
- src/Components/Shortcut/shortcut.ts
- src/Components/Theme/theme.json
- src/Components/Theme/theme.ts
- src/index.html
- src/index.ts
Sometimes it is quite hard to find files/dirs if you don't know where it is located and the search feature is a key to handling this.
* Added search files feature
<a href="https://gitpod.io/#https://github.com/kimlimjustin/xplorer/pull/182"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat: search files/dirs inside a directory

- src/Components/Open/displayFiles.ts
The current sort method is by brutally sorting it alphabetically, this PR intended to make it more humanly by adding feature to automatically sort the file by parsing locale information from the file name and sort it using `localeCompare`.
- Use `Intl.Collator` to compare file names
Requested on #196
@uahnbu Could you please review this PR? does this PR works well as you expected? 
<a href="https://gitpod.io/#https://github.com/kimlimjustin/xplorer/pull/198"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat: sort files by name using locale compare(#196)

- docs/docs/install.md
The previous link redirected the user to the route `https://github.com/kimlimjustin/xplorer/issues/new/, which led to github a 404 page. Changed this link to `https://github.com/kimlimjustin/xplorer/issues/new/choose`
<a href="https://gitpod.io/#https://github.com/kimlimjustin/xplorer/pull/207"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Updated link to new issue

- src/Components/Theme/theme.ts
The Xplorer theme on macOS was transparent and not working. This was caused by the `changeTheme()` function.
Image of the Problem:
> Fix: at function is not defined on macos, resulting in theme not working on macos

- README.md
- docs/docs/intro.md
Fix typo.
Fixed typo.
<a href="https://gitpod.io/#https://github.com/kimlimjustin/xplorer/pull/206"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix typo in README.md

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/storage.rs
The current approach to writing down users' preference settings is by writing in text format, as a result, it's easy to be read by other applications leading to security concerns.  This PR intended to make it a little bit "harder" by using `bincode` serialize and deserialize method. 
* add `bincode` dependency
* use `bincode` to serialize/deserialize storage data
<a href="https://gitpod.io/#https://github.com/kimlimjustin/xplorer/pull/216"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> feat: using bincode to serialize/deserialize storage data

- src/Components/ContextMenu/configs/bodyMenu.config.ts
- src/Components/ContextMenu/configs/fileMenu.config.ts
- src/Components/ContextMenu/configs/multipleSelectedMenu.config.ts
- src/Components/ContextMenu/contextMenu.ts
- src/Components/Drives/drives.ts
- src/Components/Files/File Operation/cut.ts
- src/Components/Files/File Operation/location.ts
- src/Components/Files/File Operation/rename.ts
- src/Components/Files/File Operation/select.ts
- src/Components/Functions/changePosition.ts
- src/Components/Layout/hover.ts
- src/Components/Open/displayFiles.ts
- src/Components/Open/open.ts
- src/Components/Open/recent.ts
- src/Components/Properties/properties.ts
- src/Components/Shortcut/shortcut.ts
`escape` and `unescape` have been deprecated and are not recommended to be used again. 
Ref: https://stackoverflow.com/questions/75980/when-are-you-supposed-to-use-escape-instead-of-encodeuri-encodeuricomponent
- replace `escape` and `unescape` with `encodeURI` and `decodeURI`.
- https://github.com/kimlimjustin/xplorer/pull/225#pullrequestreview-866334386
- https://262.ecma-international.org/9.0/#sec-escape-string
@uahnbu could you please review this?
<a href="https://gitpod.io/#https://github.com/kimlimjustin/xplorer/pull/226"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> refactor: use `encodeURI` and `decodeURI` instead of `escape` and `unescape`

- api/web/src/main.rs
I had fun doing it.
Removed unused import under linux. The import is only used under windows.
<a href="https://gitpod.io/#https://github.com/kimlimjustin/xplorer/pull/235"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Removed unused import

- README.md
The Community Contributing Links were missing the `docs` segment.
Fixed the Community Contributing Links by adding the missing URL Segment.
> fix(readme): fixed the contributing links

- src/Components/Theme/theme.ts
https://github.com/kimlimjustin/xplorer/issues/252
Change e.target to e.currentTarget, so effect coordinates would be calculated from the parent tab element, and not the hovered child elements like title, or close button.
<a href="https://gitpod.io/#https://github.com/kimlimjustin/xplorer/pull/253"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix tab hover effect flickering when hover tab title

- README.md
Tauri does not use Microsoft Edge on MacOS, Linux or any other platform.
<a href="https://gitpod.io/#https://github.com/kimlimjustin/xplorer/pull/260"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Tauri does use OS specific webview

- src/Components/ContextMenu/contextMenu.scss
[#281](https://github.com/kimlimjustin/xplorer/issues/281)
Add `pointer-events:none` for context menu icon.
Even when mouse stays on the icon, mousemove event still can trigger on contextmenu-item so that submenu will not disappear.
> Make mousemove event trigger on contextmenu-item instead of icon
